spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bjpowernode?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1870168452
    driver-class-name: com.mysql.cj.jdbc.Driver
    #filters: stat,wall
    #max-active: 20
    druid:
      #sql监控
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123
        reset-enable: false
  #      #配置web监控和uri监控
      web-stat-filter:
        enabled: true
        #拦截地址
        url-pattern: /*
        #排除拦截
        exclusions: '*.jpg,*.js,*.css,*.png,*.gif,*.ico,/druid/*'
#
      filter:
        #配置将空
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 5000

        wall:
          enabled: true
          config:
            drop-table-allow: false
#      #stat 开启监控功能
#      #wall 开启防火墙功能
#      #监控spring
      aop-patterns: com.lyw.*
      filters: stat,wall
      max-active: 20
  jdbc:
    template:
      query-timeout: 3

  #集成redis配置
  redis:
    host: 172.20.10.3
    port: 6379
    password: root
#    connect-timeout: 3000
    lettuce:
      pool:
        max-active: 8
        #最小空闲
        min-idle: 5
    #代表操作的第几个数据库
    database: 0
    #切换客户端
    client-type: lettuce

    #当前客户端项目的指标信息送给这个端口的服务器
  boot:
    admin:
      client:
        url: http://localhost:8888
    #redis://user:password@example.com:6379
#    url:


#    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true


management:
  #代表操作所有端点
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点
  #操作单个端点
  endpoint:
    health:
      show-details: always #总是显示详细信息


#定制info endPoint
info:
  appName: liyaweiapp
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@
